In [6]:
import pandas as pd

df=pd.read_csv('Allergie_Passages_Urgences_Actes_SOS_Medecins_dpt.csv')
print(df.shape)
display(df.head(5))
display(df.tail(5))

# Je suppose que "Taux de passages aux urgences pour allergie" sera la métrique à réduire - à confirmer !

(121200, 10)

,1er jour de la semaine,Semaine,Département Code,Département,Classe d'âge,Taux de passages aux urgences pour allergie,Taux d'hospitalisations après passages aux urgences pour allergie,Taux d'actes médicaux SOS médecins pour allergie,Région Code,Région
0,2026-09-28,2026-S40,23,Creuse,Tous âges,2553.191489,4000.0,NaN,75,Nouvelle Aquitaine
1,2026-09-28,2026-S40,25,Doubs,Tous âges,489.236791,800.0,760.043431,27,Bourgogne et Franche-Comté
2,2026-09-28,2026-S40,26,Drôme,65 ans ou plus,300.300300,0.0,NaN,84,Auvergne et Rhône-Alpes
3,2026-09-28,2026-S40,27,Eure,65 ans ou plus,381.194409,0.0,NaN,28,Normandie
4,2026-09-28,2026-S40,31,Haute-Garonne,00-14 ans,608.930988,0.0,1041.666667,76,Occitanie

,1er jour de la semaine,Semaine,Département Code,Département,Classe d'âge,Taux de passages aux urgences pour allergie,Taux d'hospitalisations après passages aux urgences pour allergie,Taux d'actes médicaux SOS médecins pour allergie,Région Code,Région
121195,2021-01-04,2021-S01,43,Haute-Loire,Tous âges,0.000000,0.000000,NaN,84,Auvergne et Rhône-Alpes
121196,2021-01-04,2021-S01,45,Loiret,00-14 ans,1276.595745,2777.777778,2000.000000,24,Centre-Val de Loire
121197,2021-01-04,2021-S01,45,Loiret,Tous âges,521.415270,160.771704,2140.672783,24,Centre-Val de Loire
121198,2021-01-04,2021-S01,46,Lot,15-64 ans,0.000000,0.000000,NaN,76,Occitanie
121199,2021-01-04,2021-S01,48,Lozère,15-64 ans,0.000000,0.000000,NaN,76,Occitanie

In [11]:
df=pd.read_csv('Asthme_Passages_Urgences_Actes_SOS_Medecins_dpt.csv')
print(df.shape)
display(df.head(5))
display(df.tail(5))

# Je suppose que "Taux de passages aux urgences pour asthme" sera la métrique à réduire - à confirmer !

(121200, 10)

,Semaine,1er jour de la semaine,Département,Région,Classe d'âge,Taux de passages aux urgences pour asthme,Taux d'hospitalisations après passages aux urgences pour asthme,Taux d'actes médicaux SOS médecins pour asthme,Département Code,Région Code
0,2026-S40,2026-09-28,Haute-Corse,Corse,65 ans ou plus,318.471338,0.000000,NaN,2B,94
1,2026-S40,2026-09-28,Gard,Occitanie,15-64 ans,166.805671,270.270270,1869.158878,30,76
2,2026-S40,2026-09-28,Haute-Garonne,Occitanie,00-14 ans,2232.746955,3875.968992,1041.666667,31,76
3,2026-S40,2026-09-28,Haute-Garonne,Occitanie,65 ans ou plus,341.296928,357.781753,0.000000,31,76
4,2026-S40,2026-09-28,Gers,Occitanie,00-14 ans,2777.777778,11111.111111,NaN,32,76

,Semaine,1er jour de la semaine,Département,Région,Classe d'âge,Taux de passages aux urgences pour asthme,Taux d'hospitalisations après passages aux urgences pour asthme,Taux d'actes médicaux SOS médecins pour asthme,Département Code,Région Code
121195,2021-S01,2021-01-04,Gironde,Nouvelle Aquitaine,15-64 ans,268.714012,273.597811,928.381963,33,75
121196,2021-S01,2021-01-04,Hérault,Occitanie,Tous âges,373.532551,312.500000,1433.296582,34,76
121197,2021-S01,2021-01-04,Ille-et-Vilaine,Bretagne,00-14 ans,878.293601,0.000000,1935.483871,35,53
121198,2021-S01,2021-01-04,Ille-et-Vilaine,Bretagne,Tous âges,361.713968,453.720508,814.663951,35,53
121199,2021-S01,2021-01-04,Indre-et-Loire,Centre-Val de Loire,Tous âges,127.713921,0.000000,985.663082,37,24