But du notebook première analyse overview du fichier

In [2]:
import pandas as pd
import numpy as np

In [3]:
Merge_final = pd.read_csv("../data/final_metropole/Merge_final.csv")

Merge_final.info()

Merge_final.head()

<class 'pandas.DataFrame'>
RangeIndex: 19968 entries, 0 to 19967
Data columns (total 76 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   date_semaine                                19968 non-null  str
 1   code_dept                                   19968 non-null  object
 2   As in PM10                                  19968 non-null  float64
 3   BaP in PM10                                 19968 non-null  float64
 4   Cd in PM10                                  19968 non-null  float64
 5   Ni in PM10                                  19968 non-null  float64
 6   Pb in PM10                                  19968 non-null  float64
 7   pression_mer                                19968 non-null  float64
 8   tendance_pression_3h                        19968 non-null  float64
 9   vent_direction                              19968 non-null  float64
 10  vent_vitesse                                19968 non-null  float64
 11  temperature_kelvin                          19968 non-null  float64
 12  humidite_relative                           19968 non-null  float64
 13  visibilite                                  19968 non-null  float64
 14  pression_station                            19968 non-null  float64
 15  periode_rafale                              19968 non-null  float64
 16  precipitation_1h                            19968 non-null  float64
 17  precipitation_3h                            19968 non-null  float64
 18  precipitation_6h                            19968 non-null  float64
 19  precipitation_12h                           19968 non-null  float64
 20  precipitation_24h                           19968 non-null  float64
 21  tp_averses_ou_orages                        19968 non-null  float64
 22  tp_brouillard                               19968 non-null  float64
 23  tp_brume_fumee_ou_phenomenes_particuliers   19968 non-null  float64
 24  tp_neige_precipitation_solide               19968 non-null  float64
 25  tp_phenomenes_recents_derniere_heure        19968 non-null  float64
 26  tp_pluie_ou_bruine                          19968 non-null  float64
 27  tp_sans_precipitation_visibilite_ou_nuages  19968 non-null  float64
 28  tp_tempete_poussiere_chasse_neige           19968 non-null  float64
 29  tp_temps_inconnu                            19968 non-null  float64
 30  TousAge_allergie_urgences                   19968 non-null  float64
 31  65plus_allergie_urgences                    19968 non-null  float64
 32  0_14_allergie_urgences                      19968 non-null  float64
 33  15_64_allergie_urgences                     19968 non-null  float64
 34  0_14_asthme_urgences                        19968 non-null  float64
 35  15_64_asthme_urgences                       19968 non-null  float64
 36  TousAge_asthme_urgences                     19968 non-null  float64
 37  65plus_asthme_urgences                      19968 non-null  float64
 38  0an_bronchiolite_urgences                   19908 non-null  float64
 39  TousAge_allergie_hospitalisation            19892 non-null  float64
 40  65plus_allergie_hospitalisation             19862 non-null  float64
 41  0_14_allergie_hospitalisation               19714 non-null  float64
 42  15_64_allergie_hospitalisation              19850 non-null  float64
 43  0_14_asthme_hospitalisation                 19714 non-null  float64
 44  15_64_asthme_hospitalisation                19850 non-null  float64
 45  TousAge_asthme_hospitalisation              19892 non-null  float64
 46  65plus_asthme_hospitalisation               19862 non-null  float64
 47  0an_bronchiolite_hospitalisation            18633 non-null  float64
 48  Ntop_Maladie_Respi_Chronique_tsage_9        19968 non-null  float64
 49  Npop_Maladie_Respi_Chronique_tsage_9        19968 non-null  float64
 50  prev_Maladie_Respi_Chronique_tsage_9        19968 non-null  float64
 51  Ntop_Maladie_Respi_Chronique_0-14_9         19968 non-null  float64
 52  Ntop_Maladie_Respi_Chronique_15-64_9        19968 non-null  float64
 53  Ntop_Maladie_Respi_Chronique_65+_9          19968 non-null  float64
 54  Npop_Maladie_Respi_Chronique_0-14_9         19968 non-null  float64
 55  Npop_Maladie_Respi_Chronique_15-64_9        19968 non-null  float64
 56  Npop_Maladie_Respi_Chronique_65+_9          19968 non-null  float64
 57  prev_calc_Maladie_Respi_Chronique_0-14_9    19968 non-null  float64
 58  prev_calc_Maladie_Respi_Chronique_15-64_9   19968 non-null  float64
 59  prev_calc_Maladie_Respi_Chronique_65+_9     19968 non-null  float64
 60  nom_dep                                     19968 non-null  str
 61  pct_urbain                                  19968 non-null  float64
 62  pct_artisans                                19968 non-null  float64
 63  pct_cadres                                  19968 non-null  float64
 64  pct_prof_inter                              19968 non-null  float64
 65  pct_employes                                19968 non-null  float64
 66  pct_ouvriers                                19968 non-null  float64
 67  pct_retraites                               19968 non-null  float64
 68  pct_sans_activite                           19968 non-null  float64
 69  pct_agriculteurs                            19968 non-null  float64
 70  densite_generalistes                        19968 non-null  float64
 71  densite_pediatres                           19968 non-null  float64
 72  densite_pneumologues                        19968 non-null  float64
 73  densite_allergologues                       19968 non-null  float64
 74  densite_kines                               19968 non-null  float64
 75  sos_present                                 19968 non-null  bool
dtypes: bool(1), float64(72), object(1), str(2)
memory usage: 11.4+ MB

C:\Users\gauxm\AppData\Local\Temp\ipykernel_23404\3244748483.py:1: DtypeWarning: Columns (1: code_dept) have mixed types. Specify dtype option on import or set low_memory=False.
  Merge_final = pd.read_csv("../data/final_metropole/Merge_final.csv")

,date_semaine,code_dept,As in PM10,BaP in PM10,Cd in PM10,Ni in PM10,Pb in PM10,pression_mer,tendance_pression_3h,vent_direction,...,pct_ouvriers,pct_retraites,pct_sans_activite,pct_agriculteurs,densite_generalistes,densite_pediatres,densite_pneumologues,densite_allergologues,densite_kines,sos_present
0,2021-S01,01,0.326250,0.610000,0.0500,0.4225,0.002025,101586.607143,13.928571,258.750000,...,14.2,26.0,12.9,0.6,53.439748,6.878368,1.016517,0.290433,77.400505,False
1,2021-S02,01,0.491563,1.065833,0.1375,3.0825,0.005350,102439.285714,14.285714,191.071429,...,14.2,26.0,12.9,0.6,53.439748,6.878368,1.016517,0.290433,77.400505,False
2,2021-S03,01,0.581875,0.396667,0.0800,5.8525,0.008425,101053.392857,-43.392857,170.178571,...,14.2,26.0,12.9,0.6,53.439748,6.878368,1.016517,0.290433,77.400505,False
3,2021-S04,01,0.399687,0.385833,0.0900,3.4125,0.006250,101230.000000,-12.500000,193.750000,...,14.2,26.0,12.9,0.6,53.439748,6.878368,1.016517,0.290433,77.400505,False
4,2021-S05,01,0.390000,0.360833,0.0850,1.2350,0.004900,100684.107143,6.250000,162.857143,...,14.2,26.0,12.9,0.6,53.439748,6.878368,1.016517,0.290433,77.400505,False

In [4]:
#NA
valeurs_manquantes = Merge_final.isnull().sum()
print(valeurs_manquantes[valeurs_manquantes > 0])

# Vérification du nombre de départements et de semaines
print(f"\nNombre de départements uniques : {Merge_final['code_dept'].unique()}")
print(f"Nombre de semaines uniques     : {Merge_final['date_semaine'].unique()}")

0an_bronchiolite_urgences             60
TousAge_allergie_hospitalisation      76
65plus_allergie_hospitalisation      106
0_14_allergie_hospitalisation        254
15_64_allergie_hospitalisation       118
0_14_asthme_hospitalisation          254
15_64_asthme_hospitalisation         118
TousAge_asthme_hospitalisation        76
65plus_asthme_hospitalisation        106
0an_bronchiolite_hospitalisation    1335
dtype: int64

Nombre de départements uniques : ['01' '02' '03' '04' '05' '06' '07' '08' '09' '10' '11' '12' '13' '14'
 '15' '16' '17' '18' '19' '21' '22' '23' '24' '25' '26' '27' '28' '29'
 '2A' '2B' '30' '31' '32' '33' '34' '35' '36' '37' '38' '39' 39 40 41 42
 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66
 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90
 91 92 93 94 95]
Nombre de semaines uniques     : <StringArray>
['2021-S01', '2021-S02', '2021-S03', '2021-S04', '2021-S05', '2021-S06',
 '2021-S07', '2021-S08', '2021-S09', '2021-S10',
 ...
 '2024-S43', '2024-S44', '2024-S45', '2024-S46', '2024-S47', '2024-S48',
 '2024-S49', '2024-S50', '2024-S51', '2024-S52']
Length: 208, dtype: str

In [5]:
Merge_final.describe()

,As in PM10,BaP in PM10,Cd in PM10,Ni in PM10,Pb in PM10,pression_mer,tendance_pression_3h,vent_direction,vent_vitesse,temperature_kelvin,...,pct_employes,pct_ouvriers,pct_retraites,pct_sans_activite,pct_agriculteurs,densite_generalistes,densite_pediatres,densite_pneumologues,densite_allergologues,densite_kines
count,19968.000000,19968.000000,19968.000000,19968.000000,19968.000000,19968.000000,19968.000000,19968.000000,19968.000000,19968.000000,...,19968.000000,19968.000000,19968.000000,19968.000000,19968.000000,19968.000000,19968.000000,19968.000000,19968.000000,19968.000000
mean,0.261245,0.151671,0.057315,0.919203,0.002397,101731.132958,4.767559,186.423679,3.177440,286.248787,...,15.204167,12.438542,31.028125,14.405208,1.122917,73.910446,19.467049,1.649773,0.489102,113.342456
std,0.158136,0.293028,0.038881,2.100384,0.001894,637.609307,26.564899,47.250325,1.300443,6.412574,...,1.105875,2.491647,5.302367,2.457210,0.892056,16.386317,12.840241,0.849758,0.395713,45.027645
min,0.010000,0.000000,0.000000,0.010000,0.000000,98727.500000,-109.473684,23.392857,0.446429,268.201786,...,11.200000,4.000000,16.400000,9.900000,0.000000,44.103662,0.000000,0.000000,0.000000,47.316511
25%,0.163333,0.015000,0.033174,0.367500,0.001300,101394.642857,-9.642857,157.857143,2.267857,281.373214,...,14.600000,10.800000,28.025000,12.400000,0.500000,59.315987,10.540324,0.985602,0.262798,77.723393
50%,0.230000,0.042500,0.050000,0.547500,0.001956,101729.375000,1.250000,193.512987,2.928571,285.844643,...,15.100000,12.550000,31.100000,14.100000,1.000000,74.610765,17.485046,1.590019,0.420624,101.898786
75%,0.313535,0.170000,0.070000,0.825000,0.003036,102040.000000,12.500000,218.750000,3.839286,291.287946,...,15.700000,14.200000,35.125000,16.000000,1.500000,86.650638,24.372302,2.122395,0.619918,137.225844
max,3.530000,9.755000,1.350000,134.720000,0.052800,103774.259259,156.607143,331.785714,12.600000,302.580357,...,19.100000,17.400000,41.100000,23.300000,4.700000,125.346816,87.236090,4.344889,2.167333,269.706914

In [11]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Création des sous-graphiques côte à côte
fig = make_subplots(
    rows=1, cols=2, 
    subplot_titles=('Corrélation de Pearson (Linéaire)', 'Corrélation de Spearman (Monotone)'),
    horizontal_spacing=0.1
)

# Ajout de la heatmap Pearson
fig.add_trace(
    go.Heatmap(
        z=corr_pearson.values,
        x=corr_pearson.columns,
        y=corr_pearson.index,
        colorscale='RdBu',
        zmin=-1, zmax=1,
        colorbar=dict(len=0.75, y=0.5)
    ),
    row=1, col=1
)

# Ajout de la heatmap Spearman
fig.add_trace(
    go.Heatmap(
        z=corr_spearman.values,
        x=corr_spearman.columns,
        y=corr_spearman.index,
        colorscale='RdBu',
        zmin=-1, zmax=1,
        showscale=False # On masque la seconde barre d'échelle pour plus de clarté
    ),
    row=1, col=2
)

# Mise en page globale
fig.update_layout(
    title_text="Exploration Interactive des Corrélations - Master Dataset",
    height=800,
    width=1500,
    template="plotly_white"
)

# Masquer les étiquettes de l'axe des abscisses pour la figure de droite (col=2)
fig.update_yaxes(showticklabels=False, row=1, col=2)

# Affichage du graphique interactif
fig.show()